openapi: 3.0.3
info:
  title: Pupils API
  version: 1.0.0

paths:
  /api/pupils/courses/all:
    get:
      tags:
        - PupilsCourses
      summary: Get list of pupils with their courses and status
      operationId: getPupilsCourses
      responses:
        '200':
          description: List of pupils and their courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/pupil-course-response.yml'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: './schemas/pupil-course-error.yml'

  /api/pupils/courses:
    get:
      tags:
        - PupilsCourses
      summary: Filtered list of pupils with their courses and status
      operationId: getPupilsCoursesByName
      parameters:
        - $ref: './parameters/pupil-name.yml'
        - $ref: './parameters/course-name.yml'
      responses:
        '200':
          description: List of pupils and their courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/pupil-course-response.yml'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: './schemas/pupil-course-error.yml'

  /api/pupils/course/update:
    post:
      tags:
        - PupilsCourses
      summary: Update a course status related to a pupil
      operationId: postPupilCourseUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/pupil-course-update.yml'
      responses:
        '202':
          description: Request to update the user correctly triggered

        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: './schemas/pupil-course-error.yml'