@startuml
title Pupil Courses - Architectural Schema

actor Angular as "angular-pupils-example"

rectangle "spring-boot-pupils-example" {

  package Controller {
    component PupilsCoursesApiController
  }

  package Service {
    component PupilCourseService
    component MessagingPublisherService
    component MessagingListenerService
  }

  package Repository {
    component PupilCourseRepository
  }

  package Config {
    component PupilCourseSecurityBeanConfig
    component PupilCourseRabbitMQBeanConfig
  }
}

queue "RabbitMQ" as mq
database "PostgreSQL DB" as db
component Flyway

Angular --> PupilsCoursesApiController : HTTP GET /api/pupils/courses
PupilsCoursesApiController --> PupilCourseService : getPupilsWithCoursesByName(...)
PupilCourseService --> PupilCourseRepository
PupilCourseRepository --> db : SELECT

Angular --> PupilsCoursesApiController : HTTP POST /api/pupils/course/update
PupilsCoursesApiController --> MessagingPublisherService : publish(PupilCourseUpdate)
MessagingPublisherService --> mq : send message
mq --> MessagingListenerService : consume(PupilCourseUpdate)
MessagingListenerService --> PupilCourseService : updatePupilCourse(...)
PupilCourseService --> PupilCourseRepository : findById/save
PupilCourseRepository --> db : UPDATE status

Flyway --> db : Data Migration
PupilCourseSecurityBeanConfig ..> PupilsCoursesApiController
PupilCourseRabbitMQBeanConfig ..> MessagingPublisherService
PupilCourseRabbitMQBeanConfig ..> MessagingListenerService

@enduml