-- Insert pupils
INSERT INTO PUPIL_COURSE_SCHEMA.PUPIL (PUPIL_FIRSTNAME, PUPIL_LASTNAME)
VALUES ('Malcolm', 'In the Middle');

-- Insert pupil-course relations
INSERT INTO PUPIL_COURSE_SCHEMA.PUPIL_COURSE (ID_PUPIL, ID_COURSE, STATUS)
VALUES ((SELECT ID FROM PUPIL_COURSE_SCHEMA.PUPIL WHERE PUPIL_FIRSTNAME = 'Malcolm' AND PUPIL_LASTNAME = 'In the Middle'),
        (SELECT ID FROM PUPIL_COURSE_SCHEMA.COURSE WHERE COURSE_NAME = 'PostgreSQL Basics'),
        'COMPLETED');
