-- Insert pupils
INSERT INTO PUPIL_COURSE_SCHEMA.PUPIL (PUPIL_FIRSTNAME, PUPIL_LASTNAME)
VALUES ('Leonard', 'The big Bang Theory');

-- Insert pupil-course relations
INSERT INTO PUPIL_COURSE_SCHEMA.PUPIL_COURSE (ID_PUPIL, ID_COURSE, STATUS)
VALUES ((SELECT ID FROM PUPIL_COURSE_SCHEMA.PUPIL WHERE PUPIL_FIRSTNAME = 'Leonard' AND PUPIL_LASTNAME = 'The big Bang Theory'),
        (SELECT ID FROM PUPIL_COURSE_SCHEMA.COURSE WHERE COURSE_NAME = 'PostgreSQL Basics'),
        'NOT_STARTED');
