-- Insert pupils
INSERT INTO PUPIL_COURSE_SCHEMA.PUPIL (PUPIL_FIRSTNAME, PUPIL_LASTNAME)
VALUES ('Howard', 'Jackson');

-- Insert pupil-course relations
INSERT INTO PUPIL_COURSE_SCHEMA.PUPIL_COURSE (ID_PUPIL, ID_COURSE, STATUS)
VALUES ((SELECT ID FROM PUPIL_COURSE_SCHEMA.PUPIL WHERE PUPIL_FIRSTNAME = 'Howard' AND PUPIL_LASTNAME = 'Jackson'),
        (SELECT ID FROM PUPIL_COURSE_SCHEMA.COURSE WHERE COURSE_NAME = 'PostgreSQL Basics'),
        'IN_PROGRESS');
